name: deploy

permissions:
  id-token: write  # required for requesting the JWT
  contents: read  # required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      deployment_environment:
        description: 'environment'
        required: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: "${{ github.event.inputs.deployment_environment }}"
    env:
      ASSET_DIR: built-asset
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build assets
      uses: docker/build-push-action@v4
      with:
        context: lambda
        push: false
        outputs: type=local,dest=${{ env.ASSET_DIR }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platform: "linux/amd64"

    - name: Install python deployment dependencies
      run: pip install -r requirements.txt

    - name: Assume Github OIDC role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-west-2
        role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
        role-session-name: test-cache-layers
        
    - name: Run CDK deploy
      run: |
        npx cdk deploy --all --require-approval never
      env:
        BUILT_ASSET: ${{ env.ASSET_DIR }}
